### ISSUE TITLE
Syntax Highlighting Does Not Work Inside Function

### ISSUE THREAD

**Issue by ziazek** [claco/jasmine.vim#3]
I use MacVim, and the plugin works OK except for syntax highlighting.

Outside a function (at the top, for example), the keywords are highlighted, but within the function they lose their highlighting. 

I tried editing the syntax/jasmine.vim file but I didn't get anywhere.

**Comment by ziazek** [comment]
I found out that syntax/javascript.vim was not playing nice with this plugin.

I renamed it and the syntax works for now. I think the javascript defaults to an older version in the Applications folder. Hopefully this hack doesn't break.

**Comment by claco** [comment]
Odd. Seems to work for me. (attached).

Does vim think it's a javascript+jasmine file?
What version of vim is it? vim or macvim?

**Comment by ziazek** [comment]
I use MacVim version 7.3.&nbsp;Yes, it detects that the filetype is 'jasmine.javascript', and the syntax is 'jasmine'.&nbsp;
---Please excuse my brevity. I'm trying to win The Email Game!-----Original Message-----

Re: [GitHub] Syntax Highlighting Does Not Work Inside Function [claco/jasmine.vim GH-3]
From: claco &lt;reply i-809312-e8ee73519f6054f8e9fda790429e302158a040e1@reply.github.com&gt;To: ziazek@gmail.comDate: Thursday, April 28, 2011 at 8:12AM
Odd. Seems to work for me. (attached).Does vim think it's a javascript jasmine file?What version of vim is it? vim or macvim?-- Reply to this email directly or view it on GitHub:https://github.com/claco/jasmine.vim/issues/3#comment_1067443
