### ISSUE TITLE
snippets are not working

### ISSUE THREAD

**Issue by wasimakram** [claco/jasmine.vim#8]
Hi @claco 
i tried using your plugin again and couldn't get it working I am not sure if you are familiar with https://github.com/carlhuda/janus

steps i followed installed it by adding this to `Rakefile` using 

added `templates` to `Dirs` in `Rakefile` I checked templates and snippets do have jasmine.vim code in them...
added jasmine plugin

``` ruby
~/.vim/Rakefile
  vim_plugin_task "jasmin",           "git://github.com/claco/jasmine.vim.git"

~/.vimrc.local
  let g:jasmine_snippets_directory='~/.vim/snippets'
  let g:jasmine_templates='~/.vim/templates'
```

**Comment by claco** [comment]
Does the rest of the plugin work, like syntax and filetypes?

**Comment by claco** [comment]
Should be resolved with the latest pull requests.
